### ISSUE TITLE
Key import may cause signing key to be removed from trustdb

### ISSUE THREAD

**Issue by pstarrev** [jaymzh/pius#47]
When pius imports the keys into the temporary pius_pubring.gpg using gpg2 (gpg (GnuPG) 2.1.11) the signing key may end up being removed from the default ownertrust database ~/.gnupg/trustdb.gpg.

It's just a minor annoyance and can be worked around quite easily if you have a backup of the trustdb.

A better fix would perhaps be to add the keep-ownertrust import-option as in the below very minor mod to libpius/signer.py?

diff --git a/pius/pius-2.2.2/libpius/signer.py b/pius/pius-2.2.2/libpius/signer.py
index 977d241..bd08573 100644
--- a/pius/pius-2.2.2/libpius/signer.py
+++ b/pius/pius-2.2.2/libpius/signer.py
@@ -490,7 +490,7 @@ class PiusSigner(object):
     cmd = [self.gpg] + self.gpg_base_opts + self.gpg_quiet_opts + [
         '--no-default-keyring',
         '--keyring', self.tmp_keyring,
-        '--import-options', 'import-minimal',
+        '--import-options', 'import-minimal,keep-ownertrust',
         '--import', path,
     ]
     self._run_and_check_status(cmd)

Many thanks for providing this awesome tool.

Kind regards,
Piet

**Comment by jaymzh** [comment]
We generally use `--no-auto-check-trustdb` to prevent it fucking with the db, but this explains why that's sometimes not good enough.

I wonder if doing this blanketly can add a security issue.... it's probably fine on the temp keyrings, but not when someone uses the `--import` option where it's problematic.

without digging through the code, I don't know how easy this is... but I guess my preference would be to use that option anytime we import our signing key specifically... if you throw a PR at me that does this, that'd be awesome... otherwise I'll try to poke at this before SCALE.
